version: "3.9"
services:
  fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src/themes/afs:/var/www/html/themes/afs
      - ./src/config.php:/var/www/html/config.php
  
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_USER=dbuser
      - MARIADB_DATABASE=fossbilling
      - MARIADB_PASSWORD=bitnami
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
  
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - 8888:8080
      # - 8443:8443
    depends_on:
      - mariadb


